# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VKApp', '0003_auto_20160804_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpublicpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='checkpublicpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='CheckPublicPost',
        ),
    ]
