# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VKApp', '0004_auto_20160805_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
