# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VKApp', '0006_publicpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachments',
            new_name='photo',
        ),
    ]
